fn main() {
    let manifest_root = std::path::Path::new("../../sdks/_route-manifests");
    let app_manifest_paths = [
        manifest_root.join("app-api/sdkwork-routes-health-app-api.route-manifest.json"),
        manifest_root.join("app-api/sdkwork-routes-match-app-api.route-manifest.json"),
    ];
    let backend_manifest_path =
        manifest_root.join("backend-api/sdkwork-routes-match-backend-api.route-manifest.json");

    for path in app_manifest_paths
        .iter()
        .chain(std::iter::once(&backend_manifest_path))
    {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut app_routes = Vec::new();
    for path in app_manifest_paths {
        app_routes.extend(read_manifest(&path).routes);
    }
    let backend_routes = read_manifest(&backend_manifest_path).routes;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let generated = std::path::Path::new(&out_dir).join("xiangqi_http_routes.rs");
    std::fs::write(&generated, render_rust(&app_routes, &backend_routes))
        .expect("write generated XIANGQI http routes");
}

#[derive(Debug, serde::Deserialize)]
struct RouteManifestFile {
    routes: Vec<RouteManifestRoute>,
}

#[derive(Debug, serde::Deserialize)]
struct RouteManifestRoute {
    method: String,
    path: String,
    #[serde(rename = "operationId")]
    operation_id: String,
    tags: Vec<String>,
    auth: RouteManifestAuth,
    #[serde(default)]
    idempotent: bool,
}

#[derive(Debug, serde::Deserialize)]
struct RouteManifestAuth {
    mode: String,
}

fn read_manifest(path: &std::path::Path) -> RouteManifestFile {
    let raw = std::fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("failed to read route manifest {}: {error}", path.display())
    });
    serde_json::from_str(&raw).unwrap_or_else(|error| {
        panic!("failed to parse route manifest {}: {error}", path.display())
    })
}

fn render_rust(app_routes: &[RouteManifestRoute], backend_routes: &[RouteManifestRoute]) -> String {
    let mut output = String::from(
        "// @generated by build.rs from sdks/_route-manifests �?do not edit.\n\
use sdkwork_web_contract::{HttpMethod, HttpRoute, RouteAuth};\n\n",
    );
    output.push_str("pub const XIANGQI_APP_HTTP_ROUTES: &[HttpRoute] = &[\n");
    for route in app_routes {
        output.push_str(&render_route(route));
    }
    output.push_str("];\n\npub const XIANGQI_BACKEND_HTTP_ROUTES: &[HttpRoute] = &[\n");
    for route in backend_routes {
        output.push_str(&render_route(route));
    }
    output.push_str("];\n");
    output
}

fn render_route(route: &RouteManifestRoute) -> String {
    let method = match route.method.as_str() {
        "GET" => "HttpMethod::Get",
        "POST" => "HttpMethod::Post",
        "PUT" => "HttpMethod::Put",
        "PATCH" => "HttpMethod::Patch",
        "DELETE" => "HttpMethod::Delete",
        other => panic!("unsupported HTTP method: {other}"),
    };
    let auth = match route.auth.mode.as_str() {
        "public" => "RouteAuth::Public",
        "dual-token" => "RouteAuth::DualToken",
        "api-key" => "RouteAuth::ApiKey",
        other => panic!("unsupported auth mode: {other}"),
    };
    let tag = route.tags.first().map(String::as_str).unwrap_or("xiangqi");
    let mut line = format!(
        "    HttpRoute::new({method}, {:?}, {:?}, {:?}, {auth})",
        route.path, tag, route.operation_id
    );
    if route.idempotent {
        line.push_str(".with_idempotent(true)");
    }
    line.push_str(",\n");
    line
}
