packages:
  - "sdks/*"
  - "sdks/sdkwork-xiangqi-app-sdk/sdkwork-xiangqi-app-sdk-typescript/generated/server-openapi"
  - "sdks/sdkwork-xiangqi-backend-sdk/sdkwork-xiangqi-backend-sdk-typescript/generated/server-openapi"
  - "packages/common/XIANGQI/*"
  - "apps/sdkwork-xiangqi-pc/packages/*"
  - "../sdkwork-utils/packages/sdkwork-utils-typescript"

catalog:
  "@types/node": ^25.5.2
  typescript: ~6.0.2
